// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TicTacToe.Data.DataContext;

namespace TicTacToe.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220611171128_Game1")]
    partial class Game1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TicTacToe.Data.Model.Game", b =>
                {
                    b.Property<int>("GameId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("GameResult")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<int>("GameStateId")
                        .HasColumnType("int");

                    b.Property<string>("Player0")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.Property<string>("PlayerX")
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.HasKey("GameId");

                    b.HasIndex("GameStateId");

                    b.ToTable("Game");
                });

            modelBuilder.Entity("TicTacToe.Data.Model.GameState", b =>
                {
                    b.Property<int>("GameStateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BM")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BR")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ML")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MM")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MR")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TM")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TR")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GameStateId");

                    b.ToTable("GameState");
                });

            modelBuilder.Entity("TicTacToe.Data.Model.Game", b =>
                {
                    b.HasOne("TicTacToe.Data.Model.GameState", "GameState")
                        .WithMany()
                        .HasForeignKey("GameStateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
